version: '1'
services:
  web-server:
    image: nginx:1.11.5-alpine
    volumes:
      - ./middleware/web-server/nginx.conf:/etc/nginx/nginx.conf
      - ./middleware/web-server/services.d/usecase-local.conf:/etc/nginx/services.d/usecase-local.conf
    ports:
      - "80:80"
  usecase-app-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "test"
    ports:
      - "3306:3306"
  usecase-redis:
    image: redis:3.2.3-alpine
    ports:
      - "6379:6379"
